name: bnn_notebook_env
channels:
  - pytorch
  - conda-forge
channel_priority: strict
dependencies:
  # core
  - python=3.11
  - numpy>=1.22
  - pandas
  - scikit-learn=1.5.*
  - matplotlib-base
  - scipy
  - pyyaml
  - pillow
  - tqdm

  # PyTorch / Pyro
  - pytorch::cpuonly
  - pytorch::pytorch=2.4.*
  - pyro-ppl>=1.9

  # Jupyter
  - jupyterlab
  - notebook
  - ipykernel

  - pip